#!/bin/sh
set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

fail() {
  printf 'agent harness interface check failed: %s\n' "$*" >&2
  exit 1
}

for required_file in \
  .ai-first.toml \
  .ai-first.lock \
  .ai-first/check.py \
  AGENTS.md \
  docs/agent-harness.md \
  docs/HANDOFF.md \
  docs/PRODUCT.md \
  docs/ARCHITECTURE.md \
  docs/PUBLICATION.md \
  docs/REPO_MANIFEST.yaml \
  scripts/check-publication-boundary.py; do
  [ -s "$required_file" ] || fail "missing or empty $required_file"
done

grep -Fq -- '<!-- Generated by ai-first 1.2.0.' AGENTS.md ||
  fail "AGENTS.md generated boundary is missing"
grep -Fq -- '<!-- Generated by ai-first 1.2.0.' docs/agent-harness.md ||
  fail "docs/agent-harness.md generated boundary is missing"

expected_agents_headings=$(cat <<'HEADINGS'
## First Read
## AI-first Core Contract
## Repository Overlay
HEADINGS
)
actual_agents_headings=$(sed -n 's/^\(## .*\)$/\1/p' AGENTS.md)
[ "$actual_agents_headings" = "$expected_agents_headings" ] ||
  fail "AGENTS.md section order differs from ai-first bootstrap map"

for required_line in \
  '- Structure ID: `ai-first-harness-v1`.' \
  '- Framework version: `1.2.0`.' \
  '- Project: `jjcat`.' \
  '- Publication class: `public`.' \
  '- Generated drift check: `python3 .ai-first/check.py`.'; do
  grep -Fq -- "$required_line" docs/agent-harness.md ||
    fail "docs/agent-harness.md is missing: $required_line"
done

expected_harness_headings=$(cat <<'HEADINGS'
## Interface
## Project Objective
## Core Operating Contract
## Execution Loop
## Verification And Evidence
## Escalation
## VCS And Publish
## Harness Evaluation And Improvement
## Capability Profiles
## Project Overlay
## Related Documents
HEADINGS
)
actual_harness_headings=$(sed -n 's/^\(## .*\)$/\1/p' docs/agent-harness.md)
[ "$actual_harness_headings" = "$expected_harness_headings" ] ||
  fail "docs/agent-harness.md section order differs from ai-first-harness-v1"

expected_profile_headings=$(cat <<'HEADINGS'
### Capability Profile: vcs-jj
### Capability Profile: public-repository
### Capability Profile: openai-agent-guidance
HEADINGS
)
actual_profile_headings=$(sed -n 's/^\(### Capability Profile: .*\)$/\1/p' AGENTS.md)
[ "$actual_profile_headings" = "$expected_profile_headings" ] ||
  fail "AGENTS.md capability profile order differs from .ai-first.toml"

grep -Fq -- 'Repository Driver domain contract' AGENTS.md ||
  fail "jjcat transport contract is missing"
grep -Fq -- 'opaque single-use preview' AGENTS.md ||
  fail "jjcat mutation safety contract is missing"
grep -Fq -- '"source_kind": "release"' .ai-first.lock ||
  fail "framework release source is missing from lock"
grep -Fq -- '"source_revision": "v1.2.0"' .ai-first.lock ||
  fail "framework release tag is missing from lock"
grep -Fq -- '"source_commit": "3db2810c82d0dbab3988f3fbd77ed59bb447a9cb"' .ai-first.lock ||
  fail "framework release commit is missing from lock"

python3 .ai-first/check.py
scripts/check-publication-boundary.py

printf 'agent harness interface is valid: ai-first-harness-v1 / jjcat overlay\n'
